@startuml

class Miembro{


}

class BoardMember{

}

class Evento{
date: Date
descripcion: String
assign(l : Localizacion)) : void

}

class Conferencia{

}

class BoardMeeting{

}

class Localizacion{
descripcion : String
address : String
}

class Persona{
name: String

}

class AAUOC{
newLocation(l : Localizacion) : void
newEvent(e : Evento) : void
newPerson(p : Persona) : void
informEvent(e : Evento) : void
register(m : Miembro,e : Event) : void
}

Evento <|-- Conferencia
Evento <|-- BoardMeeting

Persona <|-- Miembro
Miembro <|-- BoardMember

AAUOC o-- Persona
AAUOC o-- Localizacion
AAUOC o-- Evento

Persona -- Conferencia

BoardMeeting -- BoardMember

Evento -- Miembro

Localizacion -- Evento

@enduml