@startuml

class Miembro{

}

class BoardMember{

}

class Evento{


}

class Conferencia{

}

class BoardMeeting{

}

class Localizacion{

}

class Persona{

}

class AAUOC{

}

Evento <|-- Conferencia
Evento <|-- BoardMeeting


@enduml