@startuml

class Miembro{


}

class BoardMember{

}

class Evento{


}

class Conferencia{

}

class BoardMeeting{

}

class Localizacion{

}

class Persona{

}

class AAUOC{
newLocation(l : Localizacion) : void
newEvent(e : Evento) : void
newPerson(p : Persona) : void
informEvent(e : Evento) : void
register(m : Miembro,e : Event) : void
}

Evento <|-- Conferencia
Evento <|-- BoardMeeting

Persona <|-- Miembro
Miembro <|-- BoardMember

AAUOC o-- Persona
AAUOC o-- Localizacion
AAUOC o-- Evento

Persona -- Conferencia

BoardMeeting -- BoardMember

Evento -- Miembro

Localizacion -- Evento

@enduml